// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

/**
 * Protobuf enum {@code pb.EJoinRet}
 */
public enum EJoinRet
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>SUCCESS = 0;</code>
   */
  SUCCESS(0),
  /**
   * <pre>
   * 房间已关闭
   * </pre>
   *
   * <code>ROOM_CLOSED = 1;</code>
   */
  ROOM_CLOSED(1),
  /**
   * <pre>
   * 房间已满员
   * </pre>
   *
   * <code>ROOM_FULL = 2;</code>
   */
  ROOM_FULL(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 成功
   * </pre>
   *
   * <code>SUCCESS = 0;</code>
   */
  public static final int SUCCESS_VALUE = 0;
  /**
   * <pre>
   * 房间已关闭
   * </pre>
   *
   * <code>ROOM_CLOSED = 1;</code>
   */
  public static final int ROOM_CLOSED_VALUE = 1;
  /**
   * <pre>
   * 房间已满员
   * </pre>
   *
   * <code>ROOM_FULL = 2;</code>
   */
  public static final int ROOM_FULL_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EJoinRet valueOf(int value) {
    return forNumber(value);
  }

  public static EJoinRet forNumber(int value) {
    switch (value) {
      case 0: return SUCCESS;
      case 1: return ROOM_CLOSED;
      case 2: return ROOM_FULL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EJoinRet>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EJoinRet> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EJoinRet>() {
          public EJoinRet findValueByNumber(int number) {
            return EJoinRet.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.huya.ig.jump.protocol.Jump.getDescriptor().getEnumTypes().get(1);
  }

  private static final EJoinRet[] VALUES = values();

  public static EJoinRet valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EJoinRet(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pb.EJoinRet)
}

