// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

/**
 * <pre>
 * 房间状态
 * </pre>
 *
 * Protobuf enum {@code pb.ERoomState}
 */
public enum ERoomState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 准备中
   * </pre>
   *
   * <code>Preparing = 0;</code>
   */
  Preparing(0),
  /**
   * <pre>
   * 游戏中
   * </pre>
   *
   * <code>Gaming = 1;</code>
   */
  Gaming(1),
  /**
   * <pre>
   * 游戏结束
   * </pre>
   *
   * <code>GameOver = 2;</code>
   */
  GameOver(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 准备中
   * </pre>
   *
   * <code>Preparing = 0;</code>
   */
  public static final int Preparing_VALUE = 0;
  /**
   * <pre>
   * 游戏中
   * </pre>
   *
   * <code>Gaming = 1;</code>
   */
  public static final int Gaming_VALUE = 1;
  /**
   * <pre>
   * 游戏结束
   * </pre>
   *
   * <code>GameOver = 2;</code>
   */
  public static final int GameOver_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ERoomState valueOf(int value) {
    return forNumber(value);
  }

  public static ERoomState forNumber(int value) {
    switch (value) {
      case 0: return Preparing;
      case 1: return Gaming;
      case 2: return GameOver;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ERoomState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ERoomState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ERoomState>() {
          public ERoomState findValueByNumber(int number) {
            return ERoomState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.huya.ig.jump.protocol.Jump.getDescriptor().getEnumTypes().get(2);
  }

  private static final ERoomState[] VALUES = values();

  public static ERoomState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ERoomState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pb.ERoomState)
}

