// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface GameStartNoticeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.GameStartNotice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 游戏时长，单位秒
   * </pre>
   *
   * <code>int32 gameDuration = 1;</code>
   */
  int getGameDuration();

  /**
   * <pre>
   *  站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 2;</code>
   */
  java.util.List<com.huya.ig.jump.protocol.Platform> 
      getPlatformsList();
  /**
   * <pre>
   *  站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 2;</code>
   */
  com.huya.ig.jump.protocol.Platform getPlatforms(int index);
  /**
   * <pre>
   *  站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 2;</code>
   */
  int getPlatformsCount();
  /**
   * <pre>
   *  站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 2;</code>
   */
  java.util.List<? extends com.huya.ig.jump.protocol.PlatformOrBuilder> 
      getPlatformsOrBuilderList();
  /**
   * <pre>
   *  站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 2;</code>
   */
  com.huya.ig.jump.protocol.PlatformOrBuilder getPlatformsOrBuilder(
      int index);
}
