// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

/**
 * Protobuf type {@code pb.JumpCmd}
 */
public  final class JumpCmd extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.JumpCmd)
    JumpCmdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JumpCmd.newBuilder() to construct.
  private JumpCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JumpCmd() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JumpCmd(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.huya.ig.jump.protocol.Position.Builder subBuilder = null;
            if (from_ != null) {
              subBuilder = from_.toBuilder();
            }
            from_ = input.readMessage(com.huya.ig.jump.protocol.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(from_);
              from_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.huya.ig.jump.protocol.Position.Builder subBuilder = null;
            if (to_ != null) {
              subBuilder = to_.toBuilder();
            }
            to_ = input.readMessage(com.huya.ig.jump.protocol.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(to_);
              to_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.huya.ig.jump.protocol.Jump.internal_static_pb_JumpCmd_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.huya.ig.jump.protocol.Jump.internal_static_pb_JumpCmd_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.huya.ig.jump.protocol.JumpCmd.class, com.huya.ig.jump.protocol.JumpCmd.Builder.class);
  }

  public static final int FROM_FIELD_NUMBER = 1;
  private com.huya.ig.jump.protocol.Position from_;
  /**
   * <pre>
   * 起跳站台
   * </pre>
   *
   * <code>.pb.Position from = 1;</code>
   */
  public boolean hasFrom() {
    return from_ != null;
  }
  /**
   * <pre>
   * 起跳站台
   * </pre>
   *
   * <code>.pb.Position from = 1;</code>
   */
  public com.huya.ig.jump.protocol.Position getFrom() {
    return from_ == null ? com.huya.ig.jump.protocol.Position.getDefaultInstance() : from_;
  }
  /**
   * <pre>
   * 起跳站台
   * </pre>
   *
   * <code>.pb.Position from = 1;</code>
   */
  public com.huya.ig.jump.protocol.PositionOrBuilder getFromOrBuilder() {
    return getFrom();
  }

  public static final int TO_FIELD_NUMBER = 2;
  private com.huya.ig.jump.protocol.Position to_;
  /**
   * <pre>
   * 抵达站台
   * </pre>
   *
   * <code>.pb.Position to = 2;</code>
   */
  public boolean hasTo() {
    return to_ != null;
  }
  /**
   * <pre>
   * 抵达站台
   * </pre>
   *
   * <code>.pb.Position to = 2;</code>
   */
  public com.huya.ig.jump.protocol.Position getTo() {
    return to_ == null ? com.huya.ig.jump.protocol.Position.getDefaultInstance() : to_;
  }
  /**
   * <pre>
   * 抵达站台
   * </pre>
   *
   * <code>.pb.Position to = 2;</code>
   */
  public com.huya.ig.jump.protocol.PositionOrBuilder getToOrBuilder() {
    return getTo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (from_ != null) {
      output.writeMessage(1, getFrom());
    }
    if (to_ != null) {
      output.writeMessage(2, getTo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (from_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFrom());
    }
    if (to_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.huya.ig.jump.protocol.JumpCmd)) {
      return super.equals(obj);
    }
    com.huya.ig.jump.protocol.JumpCmd other = (com.huya.ig.jump.protocol.JumpCmd) obj;

    boolean result = true;
    result = result && (hasFrom() == other.hasFrom());
    if (hasFrom()) {
      result = result && getFrom()
          .equals(other.getFrom());
    }
    result = result && (hasTo() == other.hasTo());
    if (hasTo()) {
      result = result && getTo()
          .equals(other.getTo());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFrom()) {
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
    }
    if (hasTo()) {
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.huya.ig.jump.protocol.JumpCmd parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.huya.ig.jump.protocol.JumpCmd prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.JumpCmd}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.JumpCmd)
      com.huya.ig.jump.protocol.JumpCmdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.huya.ig.jump.protocol.Jump.internal_static_pb_JumpCmd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.huya.ig.jump.protocol.Jump.internal_static_pb_JumpCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.huya.ig.jump.protocol.JumpCmd.class, com.huya.ig.jump.protocol.JumpCmd.Builder.class);
    }

    // Construct using com.huya.ig.jump.protocol.JumpCmd.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (fromBuilder_ == null) {
        from_ = null;
      } else {
        from_ = null;
        fromBuilder_ = null;
      }
      if (toBuilder_ == null) {
        to_ = null;
      } else {
        to_ = null;
        toBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.huya.ig.jump.protocol.Jump.internal_static_pb_JumpCmd_descriptor;
    }

    @java.lang.Override
    public com.huya.ig.jump.protocol.JumpCmd getDefaultInstanceForType() {
      return com.huya.ig.jump.protocol.JumpCmd.getDefaultInstance();
    }

    @java.lang.Override
    public com.huya.ig.jump.protocol.JumpCmd build() {
      com.huya.ig.jump.protocol.JumpCmd result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.huya.ig.jump.protocol.JumpCmd buildPartial() {
      com.huya.ig.jump.protocol.JumpCmd result = new com.huya.ig.jump.protocol.JumpCmd(this);
      if (fromBuilder_ == null) {
        result.from_ = from_;
      } else {
        result.from_ = fromBuilder_.build();
      }
      if (toBuilder_ == null) {
        result.to_ = to_;
      } else {
        result.to_ = toBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.huya.ig.jump.protocol.JumpCmd) {
        return mergeFrom((com.huya.ig.jump.protocol.JumpCmd)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.huya.ig.jump.protocol.JumpCmd other) {
      if (other == com.huya.ig.jump.protocol.JumpCmd.getDefaultInstance()) return this;
      if (other.hasFrom()) {
        mergeFrom(other.getFrom());
      }
      if (other.hasTo()) {
        mergeTo(other.getTo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.huya.ig.jump.protocol.JumpCmd parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.huya.ig.jump.protocol.JumpCmd) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.huya.ig.jump.protocol.Position from_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.huya.ig.jump.protocol.Position, com.huya.ig.jump.protocol.Position.Builder, com.huya.ig.jump.protocol.PositionOrBuilder> fromBuilder_;
    /**
     * <pre>
     * 起跳站台
     * </pre>
     *
     * <code>.pb.Position from = 1;</code>
     */
    public boolean hasFrom() {
      return fromBuilder_ != null || from_ != null;
    }
    /**
     * <pre>
     * 起跳站台
     * </pre>
     *
     * <code>.pb.Position from = 1;</code>
     */
    public com.huya.ig.jump.protocol.Position getFrom() {
      if (fromBuilder_ == null) {
        return from_ == null ? com.huya.ig.jump.protocol.Position.getDefaultInstance() : from_;
      } else {
        return fromBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 起跳站台
     * </pre>
     *
     * <code>.pb.Position from = 1;</code>
     */
    public Builder setFrom(com.huya.ig.jump.protocol.Position value) {
      if (fromBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        from_ = value;
        onChanged();
      } else {
        fromBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 起跳站台
     * </pre>
     *
     * <code>.pb.Position from = 1;</code>
     */
    public Builder setFrom(
        com.huya.ig.jump.protocol.Position.Builder builderForValue) {
      if (fromBuilder_ == null) {
        from_ = builderForValue.build();
        onChanged();
      } else {
        fromBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 起跳站台
     * </pre>
     *
     * <code>.pb.Position from = 1;</code>
     */
    public Builder mergeFrom(com.huya.ig.jump.protocol.Position value) {
      if (fromBuilder_ == null) {
        if (from_ != null) {
          from_ =
            com.huya.ig.jump.protocol.Position.newBuilder(from_).mergeFrom(value).buildPartial();
        } else {
          from_ = value;
        }
        onChanged();
      } else {
        fromBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 起跳站台
     * </pre>
     *
     * <code>.pb.Position from = 1;</code>
     */
    public Builder clearFrom() {
      if (fromBuilder_ == null) {
        from_ = null;
        onChanged();
      } else {
        from_ = null;
        fromBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 起跳站台
     * </pre>
     *
     * <code>.pb.Position from = 1;</code>
     */
    public com.huya.ig.jump.protocol.Position.Builder getFromBuilder() {
      
      onChanged();
      return getFromFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 起跳站台
     * </pre>
     *
     * <code>.pb.Position from = 1;</code>
     */
    public com.huya.ig.jump.protocol.PositionOrBuilder getFromOrBuilder() {
      if (fromBuilder_ != null) {
        return fromBuilder_.getMessageOrBuilder();
      } else {
        return from_ == null ?
            com.huya.ig.jump.protocol.Position.getDefaultInstance() : from_;
      }
    }
    /**
     * <pre>
     * 起跳站台
     * </pre>
     *
     * <code>.pb.Position from = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.huya.ig.jump.protocol.Position, com.huya.ig.jump.protocol.Position.Builder, com.huya.ig.jump.protocol.PositionOrBuilder> 
        getFromFieldBuilder() {
      if (fromBuilder_ == null) {
        fromBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.huya.ig.jump.protocol.Position, com.huya.ig.jump.protocol.Position.Builder, com.huya.ig.jump.protocol.PositionOrBuilder>(
                getFrom(),
                getParentForChildren(),
                isClean());
        from_ = null;
      }
      return fromBuilder_;
    }

    private com.huya.ig.jump.protocol.Position to_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.huya.ig.jump.protocol.Position, com.huya.ig.jump.protocol.Position.Builder, com.huya.ig.jump.protocol.PositionOrBuilder> toBuilder_;
    /**
     * <pre>
     * 抵达站台
     * </pre>
     *
     * <code>.pb.Position to = 2;</code>
     */
    public boolean hasTo() {
      return toBuilder_ != null || to_ != null;
    }
    /**
     * <pre>
     * 抵达站台
     * </pre>
     *
     * <code>.pb.Position to = 2;</code>
     */
    public com.huya.ig.jump.protocol.Position getTo() {
      if (toBuilder_ == null) {
        return to_ == null ? com.huya.ig.jump.protocol.Position.getDefaultInstance() : to_;
      } else {
        return toBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 抵达站台
     * </pre>
     *
     * <code>.pb.Position to = 2;</code>
     */
    public Builder setTo(com.huya.ig.jump.protocol.Position value) {
      if (toBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        to_ = value;
        onChanged();
      } else {
        toBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 抵达站台
     * </pre>
     *
     * <code>.pb.Position to = 2;</code>
     */
    public Builder setTo(
        com.huya.ig.jump.protocol.Position.Builder builderForValue) {
      if (toBuilder_ == null) {
        to_ = builderForValue.build();
        onChanged();
      } else {
        toBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 抵达站台
     * </pre>
     *
     * <code>.pb.Position to = 2;</code>
     */
    public Builder mergeTo(com.huya.ig.jump.protocol.Position value) {
      if (toBuilder_ == null) {
        if (to_ != null) {
          to_ =
            com.huya.ig.jump.protocol.Position.newBuilder(to_).mergeFrom(value).buildPartial();
        } else {
          to_ = value;
        }
        onChanged();
      } else {
        toBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 抵达站台
     * </pre>
     *
     * <code>.pb.Position to = 2;</code>
     */
    public Builder clearTo() {
      if (toBuilder_ == null) {
        to_ = null;
        onChanged();
      } else {
        to_ = null;
        toBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 抵达站台
     * </pre>
     *
     * <code>.pb.Position to = 2;</code>
     */
    public com.huya.ig.jump.protocol.Position.Builder getToBuilder() {
      
      onChanged();
      return getToFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 抵达站台
     * </pre>
     *
     * <code>.pb.Position to = 2;</code>
     */
    public com.huya.ig.jump.protocol.PositionOrBuilder getToOrBuilder() {
      if (toBuilder_ != null) {
        return toBuilder_.getMessageOrBuilder();
      } else {
        return to_ == null ?
            com.huya.ig.jump.protocol.Position.getDefaultInstance() : to_;
      }
    }
    /**
     * <pre>
     * 抵达站台
     * </pre>
     *
     * <code>.pb.Position to = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.huya.ig.jump.protocol.Position, com.huya.ig.jump.protocol.Position.Builder, com.huya.ig.jump.protocol.PositionOrBuilder> 
        getToFieldBuilder() {
      if (toBuilder_ == null) {
        toBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.huya.ig.jump.protocol.Position, com.huya.ig.jump.protocol.Position.Builder, com.huya.ig.jump.protocol.PositionOrBuilder>(
                getTo(),
                getParentForChildren(),
                isClean());
        to_ = null;
      }
      return toBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.JumpCmd)
  }

  // @@protoc_insertion_point(class_scope:pb.JumpCmd)
  private static final com.huya.ig.jump.protocol.JumpCmd DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.huya.ig.jump.protocol.JumpCmd();
  }

  public static com.huya.ig.jump.protocol.JumpCmd getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JumpCmd>
      PARSER = new com.google.protobuf.AbstractParser<JumpCmd>() {
    @java.lang.Override
    public JumpCmd parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JumpCmd(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JumpCmd> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JumpCmd> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.huya.ig.jump.protocol.JumpCmd getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

