// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface JumpReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.JumpReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 起跳指令
   * </pre>
   *
   * <code>.pb.JumpCmd cmd = 1;</code>
   */
  boolean hasCmd();
  /**
   * <pre>
   * 起跳指令
   * </pre>
   *
   * <code>.pb.JumpCmd cmd = 1;</code>
   */
  com.huya.ig.jump.protocol.JumpCmd getCmd();
  /**
   * <pre>
   * 起跳指令
   * </pre>
   *
   * <code>.pb.JumpCmd cmd = 1;</code>
   */
  com.huya.ig.jump.protocol.JumpCmdOrBuilder getCmdOrBuilder();
}
