// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public final class Jump {
  private Jump() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Packet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Packet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_RoomConnectedNotice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_RoomConnectedNotice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Platform_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Platform_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_SyncGameDataNotice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_SyncGameDataNotice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PlayerJoinNotice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PlayerJoinNotice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_GameStartNotice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_GameStartNotice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_GameOverNotice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_GameOverNotice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PlayerInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PlayerInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Heartbeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Heartbeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_JumpCmd_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_JumpCmd_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_JumpReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_JumpReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_JumpNotice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_JumpNotice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\njump.proto\022\002pb\"#\n\006Packet\022\013\n\003uri\030\001 \001(\005\022" +
      "\014\n\004body\030\002 \001(\014\"=\n\023RoomConnectedNotice\022\031\n\003" +
      "ret\030\001 \001(\0162\014.pb.EJoinRet\022\013\n\003uid\030\002 \001(\t\"g\n\010" +
      "Platform\022\n\n\002id\030\001 \001(\005\022\r\n\005color\030\002 \001(\005\022\014\n\004s" +
      "ize\030\003 \001(\005\022\r\n\005shape\030\004 \001(\005\022\020\n\010distance\030\005 \001" +
      "(\005\022\021\n\tdirection\030\006 \001(\005\"\235\001\n\022SyncGameDataNo" +
      "tice\022\035\n\005state\030\001 \001(\0162\016.pb.ERoomState\022\020\n\010t" +
      "imeLeft\030\002 \001(\005\022\033\n\007players\030\003 \003(\0132\n.pb.Play" +
      "er\022\030\n\004rank\030\004 \003(\0132\n.pb.Player\022\037\n\tplatform" +
      "s\030\005 \003(\0132\014.pb.Platform\".\n\020PlayerJoinNotic" +
      "e\022\032\n\006player\030\001 \001(\0132\n.pb.Player\"H\n\017GameSta" +
      "rtNotice\022\024\n\014gameDuration\030\001 \001(\005\022\037\n\tplatfo" +
      "rms\030\002 \003(\0132\014.pb.Platform\"*\n\016GameOverNotic" +
      "e\022\030\n\004rank\030\001 \003(\0132\n.pb.Player\"+\n\rPlayerInf" +
      "oReq\022\032\n\006player\030\001 \001(\0132\n.pb.Player\"\036\n\tHear" +
      "tbeat\022\021\n\ttimestamp\030\001 \001(\003\"?\n\007JumpCmd\022\032\n\004f" +
      "rom\030\001 \001(\0132\014.pb.Position\022\030\n\002to\030\002 \001(\0132\014.pb" +
      ".Position\"#\n\007JumpReq\022\030\n\003cmd\030\001 \001(\0132\013.pb.J" +
      "umpCmd\"7\n\010Position\022\n\n\002id\030\001 \001(\005\022\t\n\001x\030\002 \001(" +
      "\002\022\t\n\001y\030\003 \001(\002\022\t\n\001z\030\004 \001(\002\"w\n\006Player\022\013\n\003uid" +
      "\030\001 \001(\t\022\014\n\004nick\030\002 \001(\t\022\016\n\006avatar\030\003 \001(\t\022\r\n\005" +
      "score\030\004 \001(\005\022\023\n\013deviceWidth\030\005 \001(\002\022\036\n\010posi" +
      "tion\030\006 \001(\0132\014.pb.Position\"B\n\nJumpNotice\022\032" +
      "\n\006player\030\001 \001(\0132\n.pb.Player\022\030\n\003cmd\030\002 \001(\0132" +
      "\013.pb.JumpCmd*\245\002\n\010Protocol\022\024\n\020Protocol_De" +
      "fault\020\000\022\017\n\nC2SJumpReq\020\320\017\022\024\n\017C2SHeartbeat" +
      "Req\020\321\017\022\025\n\020C2SPlayerInfoReq\020\322\017\022\024\n\017C2SStar" +
      "tGameReq\020\323\017\022\022\n\rS2CJumpNotice\020\270\027\022\027\n\022S2CHe" +
      "artbeatNotice\020\271\027\022\026\n\021S2CGameOverNotice\020\272\027" +
      "\022\027\n\022S2CGameStartNotice\020\273\027\022\032\n\025S2CSyncGame" +
      "DataNotice\020\274\027\022\030\n\023S2CPlayerJoinNotice\020\275\027\022" +
      "\033\n\026S2CRoomConnectedNotice\020\276\027*7\n\010EJoinRet" +
      "\022\013\n\007SUCCESS\020\000\022\017\n\013ROOM_CLOSED\020\001\022\r\n\tROOM_F" +
      "ULL\020\002*5\n\nERoomState\022\r\n\tPreparing\020\000\022\n\n\006Ga" +
      "ming\020\001\022\014\n\010GameOver\020\002B \n\031com.huya.ig.jump" +
      ".protocolP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_Packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Packet_descriptor,
        new java.lang.String[] { "Uri", "Body", });
    internal_static_pb_RoomConnectedNotice_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_RoomConnectedNotice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_RoomConnectedNotice_descriptor,
        new java.lang.String[] { "Ret", "Uid", });
    internal_static_pb_Platform_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_Platform_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Platform_descriptor,
        new java.lang.String[] { "Id", "Color", "Size", "Shape", "Distance", "Direction", });
    internal_static_pb_SyncGameDataNotice_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pb_SyncGameDataNotice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_SyncGameDataNotice_descriptor,
        new java.lang.String[] { "State", "TimeLeft", "Players", "Rank", "Platforms", });
    internal_static_pb_PlayerJoinNotice_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pb_PlayerJoinNotice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PlayerJoinNotice_descriptor,
        new java.lang.String[] { "Player", });
    internal_static_pb_GameStartNotice_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pb_GameStartNotice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_GameStartNotice_descriptor,
        new java.lang.String[] { "GameDuration", "Platforms", });
    internal_static_pb_GameOverNotice_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pb_GameOverNotice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_GameOverNotice_descriptor,
        new java.lang.String[] { "Rank", });
    internal_static_pb_PlayerInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_pb_PlayerInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PlayerInfoReq_descriptor,
        new java.lang.String[] { "Player", });
    internal_static_pb_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_pb_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Heartbeat_descriptor,
        new java.lang.String[] { "Timestamp", });
    internal_static_pb_JumpCmd_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_pb_JumpCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_JumpCmd_descriptor,
        new java.lang.String[] { "From", "To", });
    internal_static_pb_JumpReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_pb_JumpReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_JumpReq_descriptor,
        new java.lang.String[] { "Cmd", });
    internal_static_pb_Position_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_pb_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Position_descriptor,
        new java.lang.String[] { "Id", "X", "Y", "Z", });
    internal_static_pb_Player_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_pb_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Player_descriptor,
        new java.lang.String[] { "Uid", "Nick", "Avatar", "Score", "DeviceWidth", "Position", });
    internal_static_pb_JumpNotice_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_pb_JumpNotice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_JumpNotice_descriptor,
        new java.lang.String[] { "Player", "Cmd", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
