// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface JumpNoticeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.JumpNotice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pb.Player player = 1;</code>
   */
  boolean hasPlayer();
  /**
   * <code>.pb.Player player = 1;</code>
   */
  com.huya.ig.jump.protocol.Player getPlayer();
  /**
   * <code>.pb.Player player = 1;</code>
   */
  com.huya.ig.jump.protocol.PlayerOrBuilder getPlayerOrBuilder();

  /**
   * <code>.pb.JumpCmd cmd = 2;</code>
   */
  boolean hasCmd();
  /**
   * <code>.pb.JumpCmd cmd = 2;</code>
   */
  com.huya.ig.jump.protocol.JumpCmd getCmd();
  /**
   * <code>.pb.JumpCmd cmd = 2;</code>
   */
  com.huya.ig.jump.protocol.JumpCmdOrBuilder getCmdOrBuilder();
}
