// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 协议号
   * </pre>
   *
   * <code>int32 uri = 1;</code>
   */
  int getUri();

  /**
   * <pre>
   * 数据包，proto二进制
   * </pre>
   *
   * <code>bytes body = 2;</code>
   */
  com.google.protobuf.ByteString getBody();
}
