// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface PlatformOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Platform)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 站台id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   * 颜色
   * </pre>
   *
   * <code>int32 color = 2;</code>
   */
  int getColor();

  /**
   * <pre>
   * 大小
   * </pre>
   *
   * <code>int32 size = 3;</code>
   */
  int getSize();

  /**
   * <pre>
   * 形状
   * </pre>
   *
   * <code>int32 shape = 4;</code>
   */
  int getShape();

  /**
   * <pre>
   * 间距
   * </pre>
   *
   * <code>int32 distance = 5;</code>
   */
  int getDistance();

  /**
   * <pre>
   * 生成方向
   * </pre>
   *
   * <code>int32 direction = 6;</code>
   */
  int getDirection();
}
