// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface PlayerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Player)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string nick = 2;</code>
   */
  java.lang.String getNick();
  /**
   * <code>string nick = 2;</code>
   */
  com.google.protobuf.ByteString
      getNickBytes();

  /**
   * <code>string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>int32 score = 4;</code>
   */
  int getScore();

  /**
   * <code>float deviceWidth = 5;</code>
   */
  float getDeviceWidth();

  /**
   * <pre>
   * 当前站台
   * </pre>
   *
   * <code>.pb.Position position = 6;</code>
   */
  boolean hasPosition();
  /**
   * <pre>
   * 当前站台
   * </pre>
   *
   * <code>.pb.Position position = 6;</code>
   */
  com.huya.ig.jump.protocol.Position getPosition();
  /**
   * <pre>
   * 当前站台
   * </pre>
   *
   * <code>.pb.Position position = 6;</code>
   */
  com.huya.ig.jump.protocol.PositionOrBuilder getPositionOrBuilder();
}
