// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface PlayerInfoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.PlayerInfoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pb.Player player = 1;</code>
   */
  boolean hasPlayer();
  /**
   * <code>.pb.Player player = 1;</code>
   */
  com.huya.ig.jump.protocol.Player getPlayer();
  /**
   * <code>.pb.Player player = 1;</code>
   */
  com.huya.ig.jump.protocol.PlayerOrBuilder getPlayerOrBuilder();
}
