// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 站台id
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   * 玩家坐标x
   * </pre>
   *
   * <code>float x = 2;</code>
   */
  float getX();

  /**
   * <pre>
   * 玩家坐标y
   * </pre>
   *
   * <code>float y = 3;</code>
   */
  float getY();

  /**
   * <pre>
   * 玩家坐标z
   * </pre>
   *
   * <code>float z = 4;</code>
   */
  float getZ();
}
