// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

/**
 * Protobuf enum {@code pb.Protocol}
 */
public enum Protocol
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Protocol_Default = 0;</code>
   */
  Protocol_Default(0),
  /**
   * <pre>
   * 玩家起跳指令&amp;结果  JumpReq
   * </pre>
   *
   * <code>C2SJumpReq = 2000;</code>
   */
  C2SJumpReq(2000),
  /**
   * <pre>
   * 心跳包 Heartbeat
   * </pre>
   *
   * <code>C2SHeartbeatReq = 2001;</code>
   */
  C2SHeartbeatReq(2001),
  /**
   * <pre>
   * 玩家资料，玩家连接成功后，第一个数据包  PlayerInfoReq
   * </pre>
   *
   * <code>C2SPlayerInfoReq = 2002;</code>
   */
  C2SPlayerInfoReq(2002),
  /**
   * <pre>
   * 主播开始游戏
   * </pre>
   *
   * <code>C2SStartGameReq = 2003;</code>
   */
  C2SStartGameReq(2003),
  /**
   * <pre>
   * 玩家起跳消息  JumpNotice
   * </pre>
   *
   * <code>S2CJumpNotice = 3000;</code>
   */
  S2CJumpNotice(3000),
  /**
   * <pre>
   * 心跳响应 Heartbeat
   * </pre>
   *
   * <code>S2CHeartbeatNotice = 3001;</code>
   */
  S2CHeartbeatNotice(3001),
  /**
   * <pre>
   * 游戏结束 GameOverNotice
   * </pre>
   *
   * <code>S2CGameOverNotice = 3002;</code>
   */
  S2CGameOverNotice(3002),
  /**
   * <pre>
   * 游戏开始 GameStartNotice
   * </pre>
   *
   * <code>S2CGameStartNotice = 3003;</code>
   */
  S2CGameStartNotice(3003),
  /**
   * <pre>
   * 同步游戏数据，断线重连时服务器下发 SyncGameDataNotice
   * </pre>
   *
   * <code>S2CSyncGameDataNotice = 3004;</code>
   */
  S2CSyncGameDataNotice(3004),
  /**
   * <pre>
   * 玩家加入 PlayerJoinNotice
   * </pre>
   *
   * <code>S2CPlayerJoinNotice = 3005;</code>
   */
  S2CPlayerJoinNotice(3005),
  /**
   * <pre>
   * 连接房间信息  RoomConnectedNotice
   * </pre>
   *
   * <code>S2CRoomConnectedNotice = 3006;</code>
   */
  S2CRoomConnectedNotice(3006),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Protocol_Default = 0;</code>
   */
  public static final int Protocol_Default_VALUE = 0;
  /**
   * <pre>
   * 玩家起跳指令&amp;结果  JumpReq
   * </pre>
   *
   * <code>C2SJumpReq = 2000;</code>
   */
  public static final int C2SJumpReq_VALUE = 2000;
  /**
   * <pre>
   * 心跳包 Heartbeat
   * </pre>
   *
   * <code>C2SHeartbeatReq = 2001;</code>
   */
  public static final int C2SHeartbeatReq_VALUE = 2001;
  /**
   * <pre>
   * 玩家资料，玩家连接成功后，第一个数据包  PlayerInfoReq
   * </pre>
   *
   * <code>C2SPlayerInfoReq = 2002;</code>
   */
  public static final int C2SPlayerInfoReq_VALUE = 2002;
  /**
   * <pre>
   * 主播开始游戏
   * </pre>
   *
   * <code>C2SStartGameReq = 2003;</code>
   */
  public static final int C2SStartGameReq_VALUE = 2003;
  /**
   * <pre>
   * 玩家起跳消息  JumpNotice
   * </pre>
   *
   * <code>S2CJumpNotice = 3000;</code>
   */
  public static final int S2CJumpNotice_VALUE = 3000;
  /**
   * <pre>
   * 心跳响应 Heartbeat
   * </pre>
   *
   * <code>S2CHeartbeatNotice = 3001;</code>
   */
  public static final int S2CHeartbeatNotice_VALUE = 3001;
  /**
   * <pre>
   * 游戏结束 GameOverNotice
   * </pre>
   *
   * <code>S2CGameOverNotice = 3002;</code>
   */
  public static final int S2CGameOverNotice_VALUE = 3002;
  /**
   * <pre>
   * 游戏开始 GameStartNotice
   * </pre>
   *
   * <code>S2CGameStartNotice = 3003;</code>
   */
  public static final int S2CGameStartNotice_VALUE = 3003;
  /**
   * <pre>
   * 同步游戏数据，断线重连时服务器下发 SyncGameDataNotice
   * </pre>
   *
   * <code>S2CSyncGameDataNotice = 3004;</code>
   */
  public static final int S2CSyncGameDataNotice_VALUE = 3004;
  /**
   * <pre>
   * 玩家加入 PlayerJoinNotice
   * </pre>
   *
   * <code>S2CPlayerJoinNotice = 3005;</code>
   */
  public static final int S2CPlayerJoinNotice_VALUE = 3005;
  /**
   * <pre>
   * 连接房间信息  RoomConnectedNotice
   * </pre>
   *
   * <code>S2CRoomConnectedNotice = 3006;</code>
   */
  public static final int S2CRoomConnectedNotice_VALUE = 3006;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Protocol valueOf(int value) {
    return forNumber(value);
  }

  public static Protocol forNumber(int value) {
    switch (value) {
      case 0: return Protocol_Default;
      case 2000: return C2SJumpReq;
      case 2001: return C2SHeartbeatReq;
      case 2002: return C2SPlayerInfoReq;
      case 2003: return C2SStartGameReq;
      case 3000: return S2CJumpNotice;
      case 3001: return S2CHeartbeatNotice;
      case 3002: return S2CGameOverNotice;
      case 3003: return S2CGameStartNotice;
      case 3004: return S2CSyncGameDataNotice;
      case 3005: return S2CPlayerJoinNotice;
      case 3006: return S2CRoomConnectedNotice;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Protocol>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Protocol> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Protocol>() {
          public Protocol findValueByNumber(int number) {
            return Protocol.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.huya.ig.jump.protocol.Jump.getDescriptor().getEnumTypes().get(0);
  }

  private static final Protocol[] VALUES = values();

  public static Protocol valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Protocol(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pb.Protocol)
}

