// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface RoomConnectedNoticeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.RoomConnectedNotice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pb.EJoinRet ret = 1;</code>
   */
  int getRetValue();
  /**
   * <code>.pb.EJoinRet ret = 1;</code>
   */
  com.huya.ig.jump.protocol.EJoinRet getRet();

  /**
   * <code>string uid = 2;</code>
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 2;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
