// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

public interface SyncGameDataNoticeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.SyncGameDataNotice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 当前房间状态
   * </pre>
   *
   * <code>.pb.ERoomState state = 1;</code>
   */
  int getStateValue();
  /**
   * <pre>
   * 当前房间状态
   * </pre>
   *
   * <code>.pb.ERoomState state = 1;</code>
   */
  com.huya.ig.jump.protocol.ERoomState getState();

  /**
   * <pre>
   * 如果是游戏中，剩余游戏时间，单位秒
   * </pre>
   *
   * <code>int32 timeLeft = 2;</code>
   */
  int getTimeLeft();

  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  java.util.List<com.huya.ig.jump.protocol.Player> 
      getPlayersList();
  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  com.huya.ig.jump.protocol.Player getPlayers(int index);
  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  int getPlayersCount();
  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  java.util.List<? extends com.huya.ig.jump.protocol.PlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  com.huya.ig.jump.protocol.PlayerOrBuilder getPlayersOrBuilder(
      int index);

  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  java.util.List<com.huya.ig.jump.protocol.Player> 
      getRankList();
  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  com.huya.ig.jump.protocol.Player getRank(int index);
  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  int getRankCount();
  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  java.util.List<? extends com.huya.ig.jump.protocol.PlayerOrBuilder> 
      getRankOrBuilderList();
  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  com.huya.ig.jump.protocol.PlayerOrBuilder getRankOrBuilder(
      int index);

  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  java.util.List<com.huya.ig.jump.protocol.Platform> 
      getPlatformsList();
  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  com.huya.ig.jump.protocol.Platform getPlatforms(int index);
  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  int getPlatformsCount();
  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  java.util.List<? extends com.huya.ig.jump.protocol.PlatformOrBuilder> 
      getPlatformsOrBuilderList();
  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  com.huya.ig.jump.protocol.PlatformOrBuilder getPlatformsOrBuilder(
      int index);
}
