// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jump.proto

package com.huya.ig.jump.protocol;

/**
 * Protobuf type {@code pb.SyncGameDataNotice}
 */
public  final class SyncGameDataNotice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pb.SyncGameDataNotice)
    SyncGameDataNoticeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SyncGameDataNotice.newBuilder() to construct.
  private SyncGameDataNotice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SyncGameDataNotice() {
    state_ = 0;
    timeLeft_ = 0;
    players_ = java.util.Collections.emptyList();
    rank_ = java.util.Collections.emptyList();
    platforms_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SyncGameDataNotice(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            state_ = rawValue;
            break;
          }
          case 16: {

            timeLeft_ = input.readInt32();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              players_ = new java.util.ArrayList<com.huya.ig.jump.protocol.Player>();
              mutable_bitField0_ |= 0x00000004;
            }
            players_.add(
                input.readMessage(com.huya.ig.jump.protocol.Player.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              rank_ = new java.util.ArrayList<com.huya.ig.jump.protocol.Player>();
              mutable_bitField0_ |= 0x00000008;
            }
            rank_.add(
                input.readMessage(com.huya.ig.jump.protocol.Player.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              platforms_ = new java.util.ArrayList<com.huya.ig.jump.protocol.Platform>();
              mutable_bitField0_ |= 0x00000010;
            }
            platforms_.add(
                input.readMessage(com.huya.ig.jump.protocol.Platform.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        players_ = java.util.Collections.unmodifiableList(players_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        rank_ = java.util.Collections.unmodifiableList(rank_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        platforms_ = java.util.Collections.unmodifiableList(platforms_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.huya.ig.jump.protocol.Jump.internal_static_pb_SyncGameDataNotice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.huya.ig.jump.protocol.Jump.internal_static_pb_SyncGameDataNotice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.huya.ig.jump.protocol.SyncGameDataNotice.class, com.huya.ig.jump.protocol.SyncGameDataNotice.Builder.class);
  }

  private int bitField0_;
  public static final int STATE_FIELD_NUMBER = 1;
  private int state_;
  /**
   * <pre>
   * 当前房间状态
   * </pre>
   *
   * <code>.pb.ERoomState state = 1;</code>
   */
  public int getStateValue() {
    return state_;
  }
  /**
   * <pre>
   * 当前房间状态
   * </pre>
   *
   * <code>.pb.ERoomState state = 1;</code>
   */
  public com.huya.ig.jump.protocol.ERoomState getState() {
    @SuppressWarnings("deprecation")
    com.huya.ig.jump.protocol.ERoomState result = com.huya.ig.jump.protocol.ERoomState.valueOf(state_);
    return result == null ? com.huya.ig.jump.protocol.ERoomState.UNRECOGNIZED : result;
  }

  public static final int TIMELEFT_FIELD_NUMBER = 2;
  private int timeLeft_;
  /**
   * <pre>
   * 如果是游戏中，剩余游戏时间，单位秒
   * </pre>
   *
   * <code>int32 timeLeft = 2;</code>
   */
  public int getTimeLeft() {
    return timeLeft_;
  }

  public static final int PLAYERS_FIELD_NUMBER = 3;
  private java.util.List<com.huya.ig.jump.protocol.Player> players_;
  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  public java.util.List<com.huya.ig.jump.protocol.Player> getPlayersList() {
    return players_;
  }
  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  public java.util.List<? extends com.huya.ig.jump.protocol.PlayerOrBuilder> 
      getPlayersOrBuilderList() {
    return players_;
  }
  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  public int getPlayersCount() {
    return players_.size();
  }
  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  public com.huya.ig.jump.protocol.Player getPlayers(int index) {
    return players_.get(index);
  }
  /**
   * <pre>
   * 玩家当前状态
   * </pre>
   *
   * <code>repeated .pb.Player players = 3;</code>
   */
  public com.huya.ig.jump.protocol.PlayerOrBuilder getPlayersOrBuilder(
      int index) {
    return players_.get(index);
  }

  public static final int RANK_FIELD_NUMBER = 4;
  private java.util.List<com.huya.ig.jump.protocol.Player> rank_;
  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  public java.util.List<com.huya.ig.jump.protocol.Player> getRankList() {
    return rank_;
  }
  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  public java.util.List<? extends com.huya.ig.jump.protocol.PlayerOrBuilder> 
      getRankOrBuilderList() {
    return rank_;
  }
  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  public int getRankCount() {
    return rank_.size();
  }
  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  public com.huya.ig.jump.protocol.Player getRank(int index) {
    return rank_.get(index);
  }
  /**
   * <pre>
   * gameOver时返回排行榜
   * </pre>
   *
   * <code>repeated .pb.Player rank = 4;</code>
   */
  public com.huya.ig.jump.protocol.PlayerOrBuilder getRankOrBuilder(
      int index) {
    return rank_.get(index);
  }

  public static final int PLATFORMS_FIELD_NUMBER = 5;
  private java.util.List<com.huya.ig.jump.protocol.Platform> platforms_;
  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  public java.util.List<com.huya.ig.jump.protocol.Platform> getPlatformsList() {
    return platforms_;
  }
  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  public java.util.List<? extends com.huya.ig.jump.protocol.PlatformOrBuilder> 
      getPlatformsOrBuilderList() {
    return platforms_;
  }
  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  public int getPlatformsCount() {
    return platforms_.size();
  }
  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  public com.huya.ig.jump.protocol.Platform getPlatforms(int index) {
    return platforms_.get(index);
  }
  /**
   * <pre>
   * 站台
   * </pre>
   *
   * <code>repeated .pb.Platform platforms = 5;</code>
   */
  public com.huya.ig.jump.protocol.PlatformOrBuilder getPlatformsOrBuilder(
      int index) {
    return platforms_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (state_ != com.huya.ig.jump.protocol.ERoomState.Preparing.getNumber()) {
      output.writeEnum(1, state_);
    }
    if (timeLeft_ != 0) {
      output.writeInt32(2, timeLeft_);
    }
    for (int i = 0; i < players_.size(); i++) {
      output.writeMessage(3, players_.get(i));
    }
    for (int i = 0; i < rank_.size(); i++) {
      output.writeMessage(4, rank_.get(i));
    }
    for (int i = 0; i < platforms_.size(); i++) {
      output.writeMessage(5, platforms_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (state_ != com.huya.ig.jump.protocol.ERoomState.Preparing.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, state_);
    }
    if (timeLeft_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, timeLeft_);
    }
    for (int i = 0; i < players_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, players_.get(i));
    }
    for (int i = 0; i < rank_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, rank_.get(i));
    }
    for (int i = 0; i < platforms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, platforms_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.huya.ig.jump.protocol.SyncGameDataNotice)) {
      return super.equals(obj);
    }
    com.huya.ig.jump.protocol.SyncGameDataNotice other = (com.huya.ig.jump.protocol.SyncGameDataNotice) obj;

    boolean result = true;
    result = result && state_ == other.state_;
    result = result && (getTimeLeft()
        == other.getTimeLeft());
    result = result && getPlayersList()
        .equals(other.getPlayersList());
    result = result && getRankList()
        .equals(other.getRankList());
    result = result && getPlatformsList()
        .equals(other.getPlatformsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + TIMELEFT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeLeft();
    if (getPlayersCount() > 0) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayersList().hashCode();
    }
    if (getRankCount() > 0) {
      hash = (37 * hash) + RANK_FIELD_NUMBER;
      hash = (53 * hash) + getRankList().hashCode();
    }
    if (getPlatformsCount() > 0) {
      hash = (37 * hash) + PLATFORMS_FIELD_NUMBER;
      hash = (53 * hash) + getPlatformsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.huya.ig.jump.protocol.SyncGameDataNotice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.huya.ig.jump.protocol.SyncGameDataNotice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pb.SyncGameDataNotice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pb.SyncGameDataNotice)
      com.huya.ig.jump.protocol.SyncGameDataNoticeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.huya.ig.jump.protocol.Jump.internal_static_pb_SyncGameDataNotice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.huya.ig.jump.protocol.Jump.internal_static_pb_SyncGameDataNotice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.huya.ig.jump.protocol.SyncGameDataNotice.class, com.huya.ig.jump.protocol.SyncGameDataNotice.Builder.class);
    }

    // Construct using com.huya.ig.jump.protocol.SyncGameDataNotice.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPlayersFieldBuilder();
        getRankFieldBuilder();
        getPlatformsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      state_ = 0;

      timeLeft_ = 0;

      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        playersBuilder_.clear();
      }
      if (rankBuilder_ == null) {
        rank_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        rankBuilder_.clear();
      }
      if (platformsBuilder_ == null) {
        platforms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        platformsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.huya.ig.jump.protocol.Jump.internal_static_pb_SyncGameDataNotice_descriptor;
    }

    @java.lang.Override
    public com.huya.ig.jump.protocol.SyncGameDataNotice getDefaultInstanceForType() {
      return com.huya.ig.jump.protocol.SyncGameDataNotice.getDefaultInstance();
    }

    @java.lang.Override
    public com.huya.ig.jump.protocol.SyncGameDataNotice build() {
      com.huya.ig.jump.protocol.SyncGameDataNotice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.huya.ig.jump.protocol.SyncGameDataNotice buildPartial() {
      com.huya.ig.jump.protocol.SyncGameDataNotice result = new com.huya.ig.jump.protocol.SyncGameDataNotice(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.state_ = state_;
      result.timeLeft_ = timeLeft_;
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          players_ = java.util.Collections.unmodifiableList(players_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.players_ = players_;
      } else {
        result.players_ = playersBuilder_.build();
      }
      if (rankBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          rank_ = java.util.Collections.unmodifiableList(rank_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.rank_ = rank_;
      } else {
        result.rank_ = rankBuilder_.build();
      }
      if (platformsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          platforms_ = java.util.Collections.unmodifiableList(platforms_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.platforms_ = platforms_;
      } else {
        result.platforms_ = platformsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.huya.ig.jump.protocol.SyncGameDataNotice) {
        return mergeFrom((com.huya.ig.jump.protocol.SyncGameDataNotice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.huya.ig.jump.protocol.SyncGameDataNotice other) {
      if (other == com.huya.ig.jump.protocol.SyncGameDataNotice.getDefaultInstance()) return this;
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (other.getTimeLeft() != 0) {
        setTimeLeft(other.getTimeLeft());
      }
      if (playersBuilder_ == null) {
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
      } else {
        if (!other.players_.isEmpty()) {
          if (playersBuilder_.isEmpty()) {
            playersBuilder_.dispose();
            playersBuilder_ = null;
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000004);
            playersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlayersFieldBuilder() : null;
          } else {
            playersBuilder_.addAllMessages(other.players_);
          }
        }
      }
      if (rankBuilder_ == null) {
        if (!other.rank_.isEmpty()) {
          if (rank_.isEmpty()) {
            rank_ = other.rank_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureRankIsMutable();
            rank_.addAll(other.rank_);
          }
          onChanged();
        }
      } else {
        if (!other.rank_.isEmpty()) {
          if (rankBuilder_.isEmpty()) {
            rankBuilder_.dispose();
            rankBuilder_ = null;
            rank_ = other.rank_;
            bitField0_ = (bitField0_ & ~0x00000008);
            rankBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRankFieldBuilder() : null;
          } else {
            rankBuilder_.addAllMessages(other.rank_);
          }
        }
      }
      if (platformsBuilder_ == null) {
        if (!other.platforms_.isEmpty()) {
          if (platforms_.isEmpty()) {
            platforms_ = other.platforms_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePlatformsIsMutable();
            platforms_.addAll(other.platforms_);
          }
          onChanged();
        }
      } else {
        if (!other.platforms_.isEmpty()) {
          if (platformsBuilder_.isEmpty()) {
            platformsBuilder_.dispose();
            platformsBuilder_ = null;
            platforms_ = other.platforms_;
            bitField0_ = (bitField0_ & ~0x00000010);
            platformsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPlatformsFieldBuilder() : null;
          } else {
            platformsBuilder_.addAllMessages(other.platforms_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.huya.ig.jump.protocol.SyncGameDataNotice parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.huya.ig.jump.protocol.SyncGameDataNotice) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int state_ = 0;
    /**
     * <pre>
     * 当前房间状态
     * </pre>
     *
     * <code>.pb.ERoomState state = 1;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * 当前房间状态
     * </pre>
     *
     * <code>.pb.ERoomState state = 1;</code>
     */
    public Builder setStateValue(int value) {
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前房间状态
     * </pre>
     *
     * <code>.pb.ERoomState state = 1;</code>
     */
    public com.huya.ig.jump.protocol.ERoomState getState() {
      @SuppressWarnings("deprecation")
      com.huya.ig.jump.protocol.ERoomState result = com.huya.ig.jump.protocol.ERoomState.valueOf(state_);
      return result == null ? com.huya.ig.jump.protocol.ERoomState.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 当前房间状态
     * </pre>
     *
     * <code>.pb.ERoomState state = 1;</code>
     */
    public Builder setState(com.huya.ig.jump.protocol.ERoomState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前房间状态
     * </pre>
     *
     * <code>.pb.ERoomState state = 1;</code>
     */
    public Builder clearState() {
      
      state_ = 0;
      onChanged();
      return this;
    }

    private int timeLeft_ ;
    /**
     * <pre>
     * 如果是游戏中，剩余游戏时间，单位秒
     * </pre>
     *
     * <code>int32 timeLeft = 2;</code>
     */
    public int getTimeLeft() {
      return timeLeft_;
    }
    /**
     * <pre>
     * 如果是游戏中，剩余游戏时间，单位秒
     * </pre>
     *
     * <code>int32 timeLeft = 2;</code>
     */
    public Builder setTimeLeft(int value) {
      
      timeLeft_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 如果是游戏中，剩余游戏时间，单位秒
     * </pre>
     *
     * <code>int32 timeLeft = 2;</code>
     */
    public Builder clearTimeLeft() {
      
      timeLeft_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.huya.ig.jump.protocol.Player> players_ =
      java.util.Collections.emptyList();
    private void ensurePlayersIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        players_ = new java.util.ArrayList<com.huya.ig.jump.protocol.Player>(players_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.huya.ig.jump.protocol.Player, com.huya.ig.jump.protocol.Player.Builder, com.huya.ig.jump.protocol.PlayerOrBuilder> playersBuilder_;

    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public java.util.List<com.huya.ig.jump.protocol.Player> getPlayersList() {
      if (playersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(players_);
      } else {
        return playersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public int getPlayersCount() {
      if (playersBuilder_ == null) {
        return players_.size();
      } else {
        return playersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public com.huya.ig.jump.protocol.Player getPlayers(int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);
      } else {
        return playersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public Builder setPlayers(
        int index, com.huya.ig.jump.protocol.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.set(index, value);
        onChanged();
      } else {
        playersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public Builder setPlayers(
        int index, com.huya.ig.jump.protocol.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.set(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public Builder addPlayers(com.huya.ig.jump.protocol.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(value);
        onChanged();
      } else {
        playersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public Builder addPlayers(
        int index, com.huya.ig.jump.protocol.Player value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlayersIsMutable();
        players_.add(index, value);
        onChanged();
      } else {
        playersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public Builder addPlayers(
        com.huya.ig.jump.protocol.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public Builder addPlayers(
        int index, com.huya.ig.jump.protocol.Player.Builder builderForValue) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.add(index, builderForValue.build());
        onChanged();
      } else {
        playersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public Builder addAllPlayers(
        java.lang.Iterable<? extends com.huya.ig.jump.protocol.Player> values) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
      } else {
        playersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public Builder clearPlayers() {
      if (playersBuilder_ == null) {
        players_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        playersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public Builder removePlayers(int index) {
      if (playersBuilder_ == null) {
        ensurePlayersIsMutable();
        players_.remove(index);
        onChanged();
      } else {
        playersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public com.huya.ig.jump.protocol.Player.Builder getPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public com.huya.ig.jump.protocol.PlayerOrBuilder getPlayersOrBuilder(
        int index) {
      if (playersBuilder_ == null) {
        return players_.get(index);  } else {
        return playersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public java.util.List<? extends com.huya.ig.jump.protocol.PlayerOrBuilder> 
         getPlayersOrBuilderList() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(players_);
      }
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public com.huya.ig.jump.protocol.Player.Builder addPlayersBuilder() {
      return getPlayersFieldBuilder().addBuilder(
          com.huya.ig.jump.protocol.Player.getDefaultInstance());
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public com.huya.ig.jump.protocol.Player.Builder addPlayersBuilder(
        int index) {
      return getPlayersFieldBuilder().addBuilder(
          index, com.huya.ig.jump.protocol.Player.getDefaultInstance());
    }
    /**
     * <pre>
     * 玩家当前状态
     * </pre>
     *
     * <code>repeated .pb.Player players = 3;</code>
     */
    public java.util.List<com.huya.ig.jump.protocol.Player.Builder> 
         getPlayersBuilderList() {
      return getPlayersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.huya.ig.jump.protocol.Player, com.huya.ig.jump.protocol.Player.Builder, com.huya.ig.jump.protocol.PlayerOrBuilder> 
        getPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.huya.ig.jump.protocol.Player, com.huya.ig.jump.protocol.Player.Builder, com.huya.ig.jump.protocol.PlayerOrBuilder>(
                players_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }

    private java.util.List<com.huya.ig.jump.protocol.Player> rank_ =
      java.util.Collections.emptyList();
    private void ensureRankIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        rank_ = new java.util.ArrayList<com.huya.ig.jump.protocol.Player>(rank_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.huya.ig.jump.protocol.Player, com.huya.ig.jump.protocol.Player.Builder, com.huya.ig.jump.protocol.PlayerOrBuilder> rankBuilder_;

    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public java.util.List<com.huya.ig.jump.protocol.Player> getRankList() {
      if (rankBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rank_);
      } else {
        return rankBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public int getRankCount() {
      if (rankBuilder_ == null) {
        return rank_.size();
      } else {
        return rankBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public com.huya.ig.jump.protocol.Player getRank(int index) {
      if (rankBuilder_ == null) {
        return rank_.get(index);
      } else {
        return rankBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public Builder setRank(
        int index, com.huya.ig.jump.protocol.Player value) {
      if (rankBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRankIsMutable();
        rank_.set(index, value);
        onChanged();
      } else {
        rankBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public Builder setRank(
        int index, com.huya.ig.jump.protocol.Player.Builder builderForValue) {
      if (rankBuilder_ == null) {
        ensureRankIsMutable();
        rank_.set(index, builderForValue.build());
        onChanged();
      } else {
        rankBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public Builder addRank(com.huya.ig.jump.protocol.Player value) {
      if (rankBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRankIsMutable();
        rank_.add(value);
        onChanged();
      } else {
        rankBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public Builder addRank(
        int index, com.huya.ig.jump.protocol.Player value) {
      if (rankBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRankIsMutable();
        rank_.add(index, value);
        onChanged();
      } else {
        rankBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public Builder addRank(
        com.huya.ig.jump.protocol.Player.Builder builderForValue) {
      if (rankBuilder_ == null) {
        ensureRankIsMutable();
        rank_.add(builderForValue.build());
        onChanged();
      } else {
        rankBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public Builder addRank(
        int index, com.huya.ig.jump.protocol.Player.Builder builderForValue) {
      if (rankBuilder_ == null) {
        ensureRankIsMutable();
        rank_.add(index, builderForValue.build());
        onChanged();
      } else {
        rankBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public Builder addAllRank(
        java.lang.Iterable<? extends com.huya.ig.jump.protocol.Player> values) {
      if (rankBuilder_ == null) {
        ensureRankIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rank_);
        onChanged();
      } else {
        rankBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public Builder clearRank() {
      if (rankBuilder_ == null) {
        rank_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        rankBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public Builder removeRank(int index) {
      if (rankBuilder_ == null) {
        ensureRankIsMutable();
        rank_.remove(index);
        onChanged();
      } else {
        rankBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public com.huya.ig.jump.protocol.Player.Builder getRankBuilder(
        int index) {
      return getRankFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public com.huya.ig.jump.protocol.PlayerOrBuilder getRankOrBuilder(
        int index) {
      if (rankBuilder_ == null) {
        return rank_.get(index);  } else {
        return rankBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public java.util.List<? extends com.huya.ig.jump.protocol.PlayerOrBuilder> 
         getRankOrBuilderList() {
      if (rankBuilder_ != null) {
        return rankBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rank_);
      }
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public com.huya.ig.jump.protocol.Player.Builder addRankBuilder() {
      return getRankFieldBuilder().addBuilder(
          com.huya.ig.jump.protocol.Player.getDefaultInstance());
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public com.huya.ig.jump.protocol.Player.Builder addRankBuilder(
        int index) {
      return getRankFieldBuilder().addBuilder(
          index, com.huya.ig.jump.protocol.Player.getDefaultInstance());
    }
    /**
     * <pre>
     * gameOver时返回排行榜
     * </pre>
     *
     * <code>repeated .pb.Player rank = 4;</code>
     */
    public java.util.List<com.huya.ig.jump.protocol.Player.Builder> 
         getRankBuilderList() {
      return getRankFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.huya.ig.jump.protocol.Player, com.huya.ig.jump.protocol.Player.Builder, com.huya.ig.jump.protocol.PlayerOrBuilder> 
        getRankFieldBuilder() {
      if (rankBuilder_ == null) {
        rankBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.huya.ig.jump.protocol.Player, com.huya.ig.jump.protocol.Player.Builder, com.huya.ig.jump.protocol.PlayerOrBuilder>(
                rank_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        rank_ = null;
      }
      return rankBuilder_;
    }

    private java.util.List<com.huya.ig.jump.protocol.Platform> platforms_ =
      java.util.Collections.emptyList();
    private void ensurePlatformsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        platforms_ = new java.util.ArrayList<com.huya.ig.jump.protocol.Platform>(platforms_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.huya.ig.jump.protocol.Platform, com.huya.ig.jump.protocol.Platform.Builder, com.huya.ig.jump.protocol.PlatformOrBuilder> platformsBuilder_;

    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public java.util.List<com.huya.ig.jump.protocol.Platform> getPlatformsList() {
      if (platformsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(platforms_);
      } else {
        return platformsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public int getPlatformsCount() {
      if (platformsBuilder_ == null) {
        return platforms_.size();
      } else {
        return platformsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public com.huya.ig.jump.protocol.Platform getPlatforms(int index) {
      if (platformsBuilder_ == null) {
        return platforms_.get(index);
      } else {
        return platformsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public Builder setPlatforms(
        int index, com.huya.ig.jump.protocol.Platform value) {
      if (platformsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlatformsIsMutable();
        platforms_.set(index, value);
        onChanged();
      } else {
        platformsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public Builder setPlatforms(
        int index, com.huya.ig.jump.protocol.Platform.Builder builderForValue) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.set(index, builderForValue.build());
        onChanged();
      } else {
        platformsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public Builder addPlatforms(com.huya.ig.jump.protocol.Platform value) {
      if (platformsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlatformsIsMutable();
        platforms_.add(value);
        onChanged();
      } else {
        platformsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public Builder addPlatforms(
        int index, com.huya.ig.jump.protocol.Platform value) {
      if (platformsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlatformsIsMutable();
        platforms_.add(index, value);
        onChanged();
      } else {
        platformsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public Builder addPlatforms(
        com.huya.ig.jump.protocol.Platform.Builder builderForValue) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.add(builderForValue.build());
        onChanged();
      } else {
        platformsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public Builder addPlatforms(
        int index, com.huya.ig.jump.protocol.Platform.Builder builderForValue) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.add(index, builderForValue.build());
        onChanged();
      } else {
        platformsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public Builder addAllPlatforms(
        java.lang.Iterable<? extends com.huya.ig.jump.protocol.Platform> values) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, platforms_);
        onChanged();
      } else {
        platformsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public Builder clearPlatforms() {
      if (platformsBuilder_ == null) {
        platforms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        platformsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public Builder removePlatforms(int index) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.remove(index);
        onChanged();
      } else {
        platformsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public com.huya.ig.jump.protocol.Platform.Builder getPlatformsBuilder(
        int index) {
      return getPlatformsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public com.huya.ig.jump.protocol.PlatformOrBuilder getPlatformsOrBuilder(
        int index) {
      if (platformsBuilder_ == null) {
        return platforms_.get(index);  } else {
        return platformsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public java.util.List<? extends com.huya.ig.jump.protocol.PlatformOrBuilder> 
         getPlatformsOrBuilderList() {
      if (platformsBuilder_ != null) {
        return platformsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(platforms_);
      }
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public com.huya.ig.jump.protocol.Platform.Builder addPlatformsBuilder() {
      return getPlatformsFieldBuilder().addBuilder(
          com.huya.ig.jump.protocol.Platform.getDefaultInstance());
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public com.huya.ig.jump.protocol.Platform.Builder addPlatformsBuilder(
        int index) {
      return getPlatformsFieldBuilder().addBuilder(
          index, com.huya.ig.jump.protocol.Platform.getDefaultInstance());
    }
    /**
     * <pre>
     * 站台
     * </pre>
     *
     * <code>repeated .pb.Platform platforms = 5;</code>
     */
    public java.util.List<com.huya.ig.jump.protocol.Platform.Builder> 
         getPlatformsBuilderList() {
      return getPlatformsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.huya.ig.jump.protocol.Platform, com.huya.ig.jump.protocol.Platform.Builder, com.huya.ig.jump.protocol.PlatformOrBuilder> 
        getPlatformsFieldBuilder() {
      if (platformsBuilder_ == null) {
        platformsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.huya.ig.jump.protocol.Platform, com.huya.ig.jump.protocol.Platform.Builder, com.huya.ig.jump.protocol.PlatformOrBuilder>(
                platforms_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        platforms_ = null;
      }
      return platformsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pb.SyncGameDataNotice)
  }

  // @@protoc_insertion_point(class_scope:pb.SyncGameDataNotice)
  private static final com.huya.ig.jump.protocol.SyncGameDataNotice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.huya.ig.jump.protocol.SyncGameDataNotice();
  }

  public static com.huya.ig.jump.protocol.SyncGameDataNotice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SyncGameDataNotice>
      PARSER = new com.google.protobuf.AbstractParser<SyncGameDataNotice>() {
    @java.lang.Override
    public SyncGameDataNotice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SyncGameDataNotice(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SyncGameDataNotice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncGameDataNotice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.huya.ig.jump.protocol.SyncGameDataNotice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

